version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     NODE_ENV: development
    ports:
      - "3001:3001"
      - "4536:4536"
    expose:
      - "3001"
      - "4536"
    volumes:
      - .:/var/www/application
      - /var/www/application/node_modules
    container_name: aateam-client
