version: '3'
services:
  node:
    build:
      context: ./build
      dockerfile: ./build/Dockerfile
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=algocommunity.org
      - LETSENCRYPT_HOST=algocommunity.org
      - LETSENCRYPT_EMAIL=barry@algocommunity.org
      - VIRTUAL_PORT=80
    container_name: algocommportal
    expose:
      - 80
